### PR TITLE
TIQR-338: Fix for missing colon in enrollment URL

### PR DESCRIPTION
**Pull request by johankool**

### CODE REVIEW

**Comment by dzolnai** [comment]
How is this possible? Isn't this a server misconfiguration?

**Comment by phavekes** [comment]
The website has the same url in the QR-code as in the HREF, so it's not a server issue I think

**Comment by johankool** [comment]
Website source has: 
```
tiqrenroll://https://tiqr-demo.tiqr.org/metadata?enrollment_key=a18366e269a5774964118f5b4eefbef1 
```
App receives:
```
tiqrenroll://https//tiqr-demo.tiqr.org/metadata?enrollment_key=a18366e269a5774964118f5b4eefbef1 
```
Normally this would be the colon before the port of an URL, but if no port is set, it makes sense to strip the colon when sanitizing an URL.

**Comment by dzolnai** [comment]
Ah I see, I guess that it would be a invalid URL otherwise.

**Review by dzolnai — APPROVED** [review]

**Pull request merged**
